name: Documentation Deployment

on: 
  push:
    branches:
      - main 

env:
  AWS_REGION: ap-southeast-1 #${{ secrets.AWS_REGION }}
  ECR_REGISTRY: 024905375334.dkr.ecr.ap-southeast-1.amazonaws.com #${{ secrets.ECR_REGISTRY }}
  CLUSTER_NAME: mimo # EKS集群名

jobs:
  build: # 构建

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]  # Specify Node.js versions

    steps:
      - name: Configure AWS credentials # 配置aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::024905375334:role/github-actions
          role-session-name: github_action_Session
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR # 登录ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout # 检出分支
        uses: actions/checkout@v3

      - name: 安装依赖
        run: npm install

      - name: 构建
        run: npm run build

      - name: Clear static resource from s3
        run: |
          echo 'Clear static resource from s3.'
          npm run clear:s3

      - name: Upload static resource to s3
        run: |
          echo 'Upload static resource to s3.'
          npm run upload:s3
