name: Documentation Deployment

on: 
  push:
    branches:
      - main 

env:
  AWS_REGION: ap-southeast-1 #${{ secrets.AWS_REGION }}
  ECR_REGISTRY: 024905375334.dkr.ecr.ap-southeast-1.amazonaws.com #${{ secrets.ECR_REGISTRY }}
  CLUSTER_NAME: mimo # EKS集群名

jobs:
  build: # 构建

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]  # Specify Node.js versions

    steps:
      - name: Configure AWS credentials # 配置aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::024905375334:role/github-actions
          role-session-name: github_action_Session
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR # 登录ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout # 检出分支
        uses: actions/checkout@v3

      - name: Extract branch name # 拿分支/Tag
        id: extract_branch
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Extract image tag # 提取镜像tag 命名规则 [分支名/Tag]_[GithubCommitSHA]
        id: extract_image_tag
        shell: bash
        run: |
          echo "##[set-output name=imagetag;]$(echo ${{ steps.extract_branch.outputs.branch }}_${{ steps.extract_github_sha.outputs.githubsha }})"

      - name: 获取提交信息
        id: read-commit
        run: |
          echo "Last commit SHA: $(git rev-parse HEAD)"
          echo "Last commit message: $(git log -1 --pretty=format:%s)"
          echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "commit_msg=$(git log -1 --pretty=format:%s)" >> $GITHUB_OUTPUT

      - name: 安装依赖
        run: npm install

      - name: 构建
        run: npm run build
